apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: asia-south1-docker.pkg.dev/devproject-489317/notification-service/notification-service:commit-941c
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 4005
        envFrom:
        - secretRef:
            name: notification-service-secret
            optional: true

