apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-order
  namespace: dev
spec:
  serviceName: postgres-order
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
        - name: POSTGRES_DB
          value: "orders_db"
        - name: POSTGRES_USER
          value: "shopflow"
        - name: POSTGRES_PASSWORD
          value: "shopflow123"

