apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: asia-south1-docker.pkg.dev/devproject-489317/payment-service/payment-service:commit-941c
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 4004

